### ISSUE TITLE
Update instances of the stake_claim function to include new hooks and group args

### ISSUE THREAD

**Issue by james-allan** [Prospress/action-scheduler-custom-tables#32] opened 2018-06-26 03:03 UTC
Caught after attempting to update Subscriptions to 2.3-RC-2 on a site with this plugin active:

```
Fatal error: Declaration of Action_Scheduler\Custom_Tables\Hybrid_Store::stake_claim($max_actions = 10, ?DateTime $before_date = NULL) must be compatible with ActionScheduler_Store::stake_claim($max_actions = 10, ?DateTime $before_date = NULL, $hooks = Array, $group = '') in /srv/bindings/bb73e9145a7a4536889a5adbcdba2a20/code/wp-content/plugins/action-scheduler-custom-tables/src/Hybrid_Store.php on line 0
```

The `abstract ActionScheduler_Store::stake_claim()` function and classes overriding that function (`DB_Store` & `Hybrid_Store`) will need to be updated to include the `$hooks = array()` and `$group = ''` args.

**Comment by thenbrent** [comment] 2018-06-26 03:14
Duplicate of https://github.com/Prospress/action-scheduler-custom-tables/issues/28. 🙂

**Closed by thenbrent** 2018-06-26 03:14 UTC
